# pyproject.toml file for Databricks Serverless V1

[project]
name = "constraint-env-serverless-v1"
version = "0.1.0"
requires-python = "==3.10.*"

[tool.uv]
constraint-dependencies = [
    "anyio==3.5.0",
    "argon2-cffi==21.3.0",
    "argon2-cffi-bindings==21.2.0",
    "asttokens==2.0.5",
    "astunparse==1.6.3",
    "attrs==22.1.0",
    "backcall==0.2.0",
    "beautifulsoup4==4.11.1",
    "black==22.6.0",
    "bleach==4.1.0",
    "blinker==1.4",
    "boto3==1.24.28",
    "botocore==1.27.96",
    "cachetools==5.3.2",
    "certifi==2022.12.7",
    "cffi==1.15.1",
    "chardet==4.0.0",
    "charset-normalizer==2.0.4",
    "click==8.0.4",
    "comm==0.1.2",
    "contourpy==1.0.5",
    "cryptography==39.0.1",
    "cycler==0.11.0",
    "cython==0.29.32",
    "databricks-connect==14.3.13",
    "databricks-sdk==0.20.0",
    "debugpy==1.6.7",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "distlib==0.3.8",
    "distro==1.7.0",
    "docstring-to-markdown==0.11",
    "entrypoints==0.4",
    "executing==0.8.3",
    "facets-overview==1.1.1",
    "fastjsonschema==2.20.0",
    "filelock==3.16.1",
    "fonttools==4.25.0",
    "google-auth==2.28.1",
    "googleapis-common-protos==1.62.0",
    "grpcio==1.62.0",
    "grpcio-status==1.62.0",
    "httplib2==0.20.2",
    "idna==3.4",
    "importlib-metadata==4.6.4",
    "ipyflow-core==0.0.198",
    "ipykernel==6.25.0",
    "ipython==8.14.0",
    "ipython-genutils==0.2.0",
    "ipywidgets==7.7.2",
    "jedi==0.18.1",
    "jeepney==0.7.1",
    "jinja2==3.1.2",
    "jmespath==0.10.0",
    "joblib==1.2.0",
    "jsonschema==4.17.3",
    "jupyter-client==7.3.4",
    "jupyter-core==5.2.0",
    "jupyter-server==1.23.4",
    "jupyterlab-pygments==0.1.2",
    "jupyterlab-widgets==1.0.0",
    "keyring==23.5.0",
    "kiwisolver==1.4.4",
    "launchpadlib==1.10.16",
    "lazr-restfulclient==0.14.4",
    "lazr-uri==1.0.6",
    "lxml==4.9.1",
    "markupsafe==2.1.1",
    "matplotlib==3.7.0",
    "matplotlib-inline==0.1.6",
    "mccabe==0.7.0",
    "mistune==0.8.4",
    "more-itertools==8.10.0",
    "mypy-extensions==0.4.3",
    "nbclassic==0.5.2",
    "nbclient==0.5.13",
    "nbconvert==6.5.4",
    "nbformat==5.7.0",
    "nest-asyncio==1.5.6",
    "nodeenv==1.9.1",
    "notebook==6.5.2",
    "notebook-shim==0.2.2",
    "numpy==1.23.5",
    "oauthlib==3.2.0",
    "packaging==23.2",
    "pandas==1.5.3",
    "pandocfilters==1.5.0",
    "parso==0.8.3",
    "pathspec==0.10.3",
    "patsy==0.5.3",
    "pexpect==4.8.0",
    "pickleshare==0.7.5",
    "pillow==9.4.0",
    "platformdirs==2.5.2",
    "plotly==5.9.0",
    "pluggy==1.0.0",
    "prometheus-client==0.14.1",
    "prompt-toolkit==3.0.36",
    "protobuf==4.25.5",
    "psutil==5.9.0",
    "psycopg2==2.9.3",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.2",
    "py4j==0.10.9.7",
    "pyarrow==8.0.0",
    "pyarrow-hotfix==0.5",
    "pyasn1==0.5.1",
    "pyasn1-modules==0.3.0",
    "pyccolo==0.0.52",
    "pycparser==2.21",
    "pydantic==1.10.6",
    "pyflakes==3.1.0",
    "pygments==2.11.2",
    "pyjwt==2.3.0",
    "pyodbc==4.0.32",
    "pyparsing==3.0.9",
    "pyright==1.1.294",
    "pyrsistent==0.18.0",
    "python-dateutil==2.8.2",
    "python-lsp-jsonrpc==1.1.1",
    "python-lsp-server==1.8.0",
    "pytoolconfig==1.2.5",
    "pytz==2022.7",
    "pyzmq==23.2.0",
    "requests==2.28.1",
    "rope==1.7.0",
    "rsa==4.9",
    "s3transfer==0.6.2",
    "scikit-learn==1.1.1",
    "scipy==1.10.0",
    "seaborn==0.12.2",
    "secretstorage==3.3.1",
    "send2trash==1.8.0",
    "setuptools==80.9.0",
    "six==1.16.0",
    "sniffio==1.2.0",
    "soupsieve==2.3.2.post1",
    "ssh-import-id==5.11",
    "stack-data==0.2.0",
    "statsmodels==0.13.5",
    "tenacity==8.1.0",
    "terminado==0.17.1",
    "threadpoolctl==2.2.0",
    "tinycss2==1.2.1",
    "tokenize-rt==4.2.1",
    "tomli==2.0.1",
    "tornado==6.1",
    "traitlets==5.7.1",
    "typing-extensions==4.4.0",
    "ujson==5.4.0",
    "urllib3==1.26.14",
    "virtualenv==20.16.7",
    "wadllib==1.3.6",
    "wcwidth==0.2.5",
    "webencodings==0.5.1",
    "websocket-client==0.58.0",
    "whatthepatch==1.0.2",
    "wheel==0.45.1",
    "widgetsnbextension==3.6.1",
    "yapf==0.33.0",
    "zipp==1.0.0",
]
