# uv.toml file for 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)
constraint-dependencies = [
    "argon2-cffi==21.3.0",
    "argon2-cffi-bindings==21.2.0",
    "asttokens==2.0.5",
    "attrs==21.4.0",
    "backcall==0.2.0",
    "backports-entry-points-selectable==1.2.0",
    "beautifulsoup4==4.11.1",
    "black==22.3.0",
    "bleach==4.1.0",
    "boto3==1.21.32",
    "botocore==1.24.32",
    "certifi==2021.10.8",
    "cffi==1.15.0",
    "chardet==4.0.0",
    "charset-normalizer==2.0.4",
    "click==8.0.4",
    "cryptography==3.4.8",
    "cycler==0.11.0",
    "cython==0.29.28",
    "debugpy==1.5.1",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "distlib==0.3.6",
    "distro==1.4.0",
    "docstring-to-markdown==0.11",
    "entrypoints==0.4",
    "executing==0.8.3",
    "facets-overview==1.0.0",
    "fastjsonschema==2.16.2",
    "filelock==3.9.0",
    "fonttools==4.25.0",
    "idna==3.3",
    "ipykernel==6.15.3",
    "ipython==8.5.0",
    "ipython-genutils==0.2.0",
    "ipywidgets==7.7.2",
    "jedi==0.18.1",
    "jinja2==2.11.3",
    "jmespath==0.10.0",
    "joblib==1.1.1",
    "jsonschema==4.4.0",
    "jupyter-client==6.1.12",
    "jupyter-core==4.11.2",
    "jupyterlab-pygments==0.1.2",
    "jupyterlab-widgets==1.0.0",
    "kiwisolver==1.3.2",
    "markupsafe==2.0.1",
    "matplotlib==3.5.1",
    "matplotlib-inline==0.1.2",
    "mccabe==0.7.0",
    "mistune==0.8.4",
    "mypy-extensions==0.4.3",
    "nbclient==0.5.13",
    "nbconvert==6.4.4",
    "nbformat==5.3.0",
    "nest-asyncio==1.5.5",
    "nodeenv==1.7.0",
    "notebook==6.4.8",
    "numpy==1.21.5",
    "packaging==21.3",
    "pandas==1.4.2",
    "pandocfilters==1.5.0",
    "parso==0.8.3",
    "pathspec==0.9.0",
    "patsy==0.5.2",
    "pexpect==4.8.0",
    "pickleshare==0.7.5",
    "pillow==9.0.1",
    "platformdirs==2.6.2",
    "plotly==5.6.0",
    "pluggy==1.0.0",
    "prometheus-client==0.13.1",
    "prompt-toolkit==3.0.20",
    "protobuf==3.19.4",
    "psutil==5.8.0",
    "psycopg2==2.9.3",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.2",
    "pyarrow==7.0.0",
    "pyarrow-hotfix==0.5",
    "pycparser==2.21",
    "pyflakes==2.5.0",
    "pygments==2.11.2",
    "pyodbc==4.0.32",
    "pyparsing==3.0.4",
    "pyright==1.1.283",
    "pyrsistent==0.18.0",
    "python-dateutil==2.8.2",
    "python-lsp-jsonrpc==1.0.0",
    "python-lsp-server==1.6.0",
    "pytz==2021.3",
    "pyzmq==22.3.0",
    "requests==2.27.1",
    "requests-unixsocket==0.2.0",
    "rope==0.22.0",
    "s3transfer==0.5.0",
    "scikit-learn==1.0.2",
    "scipy==1.7.3",
    "seaborn==0.11.2",
    "send2trash==1.8.0",
    "setuptools==80.9.0",
    "six==1.16.0",
    "soupsieve==2.3.1",
    "ssh-import-id==5.10",
    "stack-data==0.2.0",
    "statsmodels==0.13.2",
    "tenacity==8.0.1",
    "terminado==0.13.1",
    "testpath==0.5.0",
    "threadpoolctl==2.2.0",
    "tokenize-rt==4.2.1",
    "tomli==1.2.2",
    "tornado==6.1",
    "traitlets==5.1.1",
    "typing-extensions==4.1.1",
    "ujson==5.1.0",
    "urllib3==1.26.9",
    "virtualenv==20.8.0",
    "wcwidth==0.2.5",
    "webencodings==0.5.1",
    "whatthepatch==1.0.4",
    "widgetsnbextension==3.6.1",
    "yapf==0.31.0",
]
